# .github/workflows/ci-pipeline.yml

name: CI/CD Test Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request: # This should be at the same indentation level as 'push'
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Root Dependencies
        run: npm install

      - name: Install Backend Dependencies
        run: npm install
        working-directory: ./node-backend

      - name: Install Frontend Dependencies
        run: npm install
        working-directory: ./react-app

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Start Backend API (for all tests)
        run: |
          export PORT=5000
          nohup npm start > backend.log 2>&1 &
          echo "Backend PID: $!" > backend_pid.txt
          echo "Waiting for backend to start on port $PORT..."
          curl --fail --retry 10 --retry-delay 5 http://localhost:$PORT/items || (echo "Backend not ready after multiple retries!" && cat backend.log && exit 1)
          echo "Backend is ready."
        working-directory: ./node-backend
        env:
          PORT: 5000

      - name: Run UI Tests
        run: npm run test:ui
      
      - name: Debug: List Workspace Contents After UI Tests
            run: |
              echo "Listing contents of current directory:"
              ls -la
              echo "Listing contents of test-results/ (if exists):"
              ls -la test-results/ || echo "test-results/ does not exist or is empty."
              echo "Listing contents of playwright-report/ (if exists):"
              ls -la playwright-report/ || echo "playwright-report/ does not exist or is empty."
              echo "Listing contents of playwright-tests/ (if exists):"
              ls -la playwright-tests/ || echo "playwright-tests/ does not exist or is empty."
              echo "Listing contents of react-app/ (if exists):"
              ls -la react-app/ || echo "react-app/ does not exist or is empty."
              echo "Listing contents of node-backend/ (if exists):"
              ls -la node-backend/ || echo "node-backend/ does not exist or is empty."
              echo "Listing ALL contents recursively:"
              ls -R


      - name: Run API Tests
        run: npm run test:api

      # CODE COVERAGE ---
      - name: Generate Code Coverage Report
        run: npm run coverage
        if: always()

      - name: Upload Code Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: coverage/
        if: always()

      - name: Upload Playwright Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-results
          path: test-results/

      - name: Upload Playwright HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: playwright-report/
